---
abstract: 'Error Page DSL for Nephia'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-ErrorPage
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Nephia::Plugin::ErrorPage:
    file: lib/Nephia/Plugin/ErrorPage.pm
    version: 0.01
requires:
  HTTP::Status: 0
  Nephia: 0.80
  Nephia::Plugin::View::MicroTemplate: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/nephia/Nephia-Plugin-ErrorPage/issues
  homepage: https://github.com/nephia/Nephia-Plugin-ErrorPage
  repository: git://github.com/nephia/Nephia-Plugin-ErrorPage.git
version: 0.01
